version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install -g serverless@3
      - echo Verifying installations...
      - serverless --version
      - python --version

  pre_build:
    commands:
      - echo Installing Serverless plugins...
      - npm install --save-dev serverless-python-requirements serverless-package-python-functions
      - echo Configuring AWS region...
      - aws configure set region $AWS_REGION
      - echo Installing Python dependencies...
      - if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "No requirements.txt found"; fi

  build:
    commands:
      - echo "Current directory contents:"
      - ls -la
      - echo "Current environment: $ENVIRONMENT"
      - echo "AWS region: $AWS_REGION"
      - echo Deploying Serverless application...
      - serverless deploy --stage $ENVIRONMENT --region $AWS_REGION --verbose

  post_build:
    commands:
      - echo Build completed on `date`
      - echo "Deployment outputs:"
      - serverless info --stage $ENVIRONMENT --verbose || echo "Info command failed, but deployment may have succeeded"

artifacts:
  files:
    - serverless.yml
    - .serverless/**/*
    - 'src/**/*'

cache:
  paths:
    - '/root/.cache/pip/**/*'
    - '/root/.npm/**/*'
    - 'node_modules/**/*'