service: 'serverless-app'

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    STAGE: ${self:provider.stage}
  
plugins:
  - serverless-python-requirements
  - serverless-package-python-functions

package:
  individually: true
  excludeDevDependencies: true

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    useStaticCache: true
  packagePythonFunctions:
    buildDir: build

functions:
  hello:
    handler: src/test.hello
    events:
      - http:
          path: hello
          method: get
  
  world:
    handler: src/test.world
    events:
      - http:
          path: world
          method: get